### ISSUE TITLE
#bug 在Android 12L上点击饼干管理无响应

### ISSUE THREAD

**Issue by UzLung1435** [re-ovo/xland#1]
clone了一份代码下来编译，发现饼干管理居然出了问题，as上也没有抓到对应的log（

**Comment by re-ovo** [comment]
因为这个我只搭了个架子，功能没写，建议用其他的第三方客户端，他们都做得不错

**Comment by re-ovo** [comment]
考虑到已经存在多个第三方客户端，我就不继续做了
